{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "smeejas.serviceAccountName" . }}
  labels:
    {{- include "smeejas.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["stable.example.com"]
  resources: ["smees"]
  verbs: ["get", "watch", "list"]
{{- end }}
